---
title: "Spatial analysis"
output: rmarkdown::html_vignette
vignette: >
  %/VignetteIndexEntry{introduction}
  %/VignetteEngine{knitr::rmarkdown}
  %/VignetteEncoding{UTF-8}
---
Please install the following dependencies before running the analysis
```{r message=FALSE}
library(Seurat)
library(dplyr)
library(sqldf)
library(ggplot2)
library(patchwork)
library(RColorBrewer)
library(ggpubr)

library(spatstat)
library(gplots)
library(corrplot)
library(stringr)

library(VennDiagram)
library(grid)#for printing PDFs off finder makrer
DiscretePalette(40, palette = "polychrome")
library(reshape2)
library(ggplot2)

#ADD YOUR STUDY NAME HERE
study_name<-"human_BRCL_Visium"
#PLEASE ADD YOUR WORKING PATH HERE
study_path<-"your_path_here/"
#MAKE A LIST OF SAMPLES THAT YOU WILL BE ANALYSING
samples <-c("002","009","010", "006")


#CREATE A FOLDER WITHIN 'study_path' as 'R'. ALL ANALYSIS WILL BE STORED HERE
save_path<-paste0(study_path,"R/")
save_on<-1

```
###AS LONG AS YOU HAVE FOLDERS STARTING WITH 'V' IN 'study' PATH AND IF YOU###
###HAVE GIVEN THE CORRECT SAMPLE NAMES (SEE 'samples' ABOVE) THE FOLLOWING CODE###
### WILL PICK UP .H5 FILES ASSOCIATED WITH THESE SAMPLES###
```{r loadSeurath5}

seuratSpatial <- list()
counter<-1
for (sample in samples){
  sample_dir <- Sys.glob(paste0(study_path,"V*/*",sample,"/"))
  sample_path <- Sys.glob(paste0(study_path,"V*/*",sample,"/","*.h5"))
  sample_path_file <- tail(strsplit(sample_path, split = "/")[[1]], n = 1)
  seuratSpatial[[sample]]<-Load10X_Spatial(
                                      sample_dir,
                                      filename = sample_path_file,
                                      assay = "Spatial",
                                      slice = sample,
                                      filter.matrix = TRUE,
                                      to.upper = FALSE
                                    )
  #THIS SETS UP META DATA 'orig.ident' AS sammple FROM samples
  seuratSpatial[[sample]]$orig.ident <- sample
  #THIS SETS UP META DATA 'group' AS current sample_group
  seuratSpatial[[sample]]$group <- sample_group[[counter]]
  #Run normalization and scaling here
  # seuratSpatial[[sample]] <- NormalizeData(seuratSpatial[[sample]])
  

  counter<-counter+1
}

```
#QC plots
```{r data_pre_processing}
#save prelim stats here.
pdf(file = paste0(save_path, "Total_BRCL_counts.pdf"))
  for(object in seuratSpatial){
    plot1 <- VlnPlot(object, features = "nCount_Spatial", pt.size = 0.1) + NoLegend()
    plot2 <- SpatialFeaturePlot(object, features = "nCount_Spatial") + theme(legend.position = "right")
    plot3 <- SpatialFeaturePlot(object, features = "nFeature_Spatial") + theme(legend.position = "right")
    print(wrap_plots(plot1, plot2, plot3))
  }
dev.off()
rm(plot1,plot2, plot3)
gc()
gc()
```
#Normalise spatial counts here and merge datasets
```{r SCTRansform, warning=FALSE}

for(sample in samples){
  print(seuratSpatial[[sample]])
  seuratSpatial[[sample]] <- SCTransform(seuratSpatial[[sample]], assay = "Spatial", verbose = FALSE, vars.to.regress = c("nCount_Spatial", "nFeature_Spatial"))
}

```


```{r Integrate only when looking at common signatures}
features <- SelectIntegrationFeatures(object.list = seuratSpatial, nfeatures = 3000)
seuratSpatial <- PrepSCTIntegration(object.list = seuratSpatial, anchor.features = features)

immune.anchors <- FindIntegrationAnchors(object.list = seuratSpatial, normalization.method = "SCT", anchor.features = features)
#rm(seuratSpatial)
gc()
BRCL_merged <- IntegrateData(anchorset = immune.anchors, normalization.method = "SCT")
```

#running UMAP/tSNE/Clustering
```{r clustering}
res=0.5
dims=30

BRCL_merged <- RunPCA(BRCL_merged, assay = "integrated", verbose = FALSE)
#non-SCT workflow start
# BRCL_skin_merged <- ScaleData(BRCL_skin_merged)
# BRCL_skin_merged <- RunPCA(BRCL_skin_merged, verbose = FALSE)
#non-SCT workflow end

ElbowPlot(BRCL_merged)
BRCL_merged <- FindNeighbors(BRCL_merged, reduction = "pca", dims = 1:dims)

BRCL_merged <- FindClusters(BRCL_merged, verbose = FALSE, resolution = res)
BRCL_merged <- RunUMAP(BRCL_merged, reduction = "pca", dims = 1:dims)
BRCL_merged <- RunTSNE(BRCL_merged, reduction = "pca", dims = 1:dims)
BRCL_merged <- PrepSCTFindMarkers(BRCL_merged, assay = "SCT")

spot_colours = c('0'='#F68282','1'='#31C53F','2'='#1FA195','3'='#B95FBB','4'='tomato3',
    '5'='#28CECA','6'='#ff9a36', '7'='#2FF18B','8'='#aeadb3', '9'='#faf4cf','10'='#CCB1F1','11'='#4B4BF7','12'='#A4DFF2','13'='#AC8F14',
     '14'='#E6C122')
#'15'='#25aff5','16'='wheat4', '17'= 'mediumorchid1', '18'= 'tomato3', '19'='darkolivegreen1')
levels(Idents(BRCL_merged))

my_cols <- spot_colours[order(as.integer(names(spot_colours)))]



pdf(paste0(save_path, "BRCL_SpatialDimPlot_PC1to",dims,res,".pdf"), width = 12)
 x<-SpatialDimPlot(BRCL_merged,crop = FALSE, pt.size.factor = 1, image.alpha =0.1,label = FALSE, label.size = 2, repel = TRUE, cols=my_cols)
  y<-SpatialDimPlot(BRCL_merged, alpha = c(0, 0), crop = FALSE, pt.size.factor = 0.9, cols=my_cols)

  for(i in 1:3){
    fig1<-x[[i]]
    #print(fig1)
    fig2<-y[[i]]
    print(ggarrange(fig1,fig2, ncol = 2))
    #print(fig2)
  }
  
dev.off()  
rm(x, y)

```
