---
title: "introduction"
output: rmarkdown::html_vignette
vignette: >
  %/VignetteIndexEntry{introduction}
  %/VignetteEngine{knitr::rmarkdown}
  %/VignetteEncoding{UTF-8}
---

```{r message=FALSE}
library(Seurat)
library(dplyr)
library(sqldf)
library(ggplot2)
library(patchwork)
library(RColorBrewer)
library(ggpubr)

library(spatstat)
library(gplots)
library(corrplot)
library(stringr)

library(VennDiagram)
library(grid)#for printing PDFs off finder makrer
DiscretePalette(40, palette = "polychrome")
library(reshape2)
library(ggplot2)

study_name<-"human_PKDL_Visium"
#PLEASE ADD YOUR WORKING PATH HERE
study_path<-"your_path_here/"

samples <-c("543", "575")
sample_label <-c("P1","P2")

#ADD GROUPS IF ANY
sample_group <-c("Poly", "Mac")
#Create a sub-folder in your 
#work path where all outputs
#will be stored
save_path<-paste0(study_path,"R/")
save_on<-1

```
LOAD H5
###AS LONG AS YOU HAVE FOLDERS STARTING WITH 'V' IN 'study' PATH AND IF YOU###
###HAVE GIVEN THE CORRECT SAMPLE NAMES (SEE 'samples' ABOVE) THE FOLLOWING CODE###
### WILL PICK UP .H5 FILES ASSOCIATED WITH THESE SAMPLES###
```{r loadSeurath5}
#READ H5
seuratSpatial <- list()
counter<-1
for (sample in samples){
  sample_dir <- Sys.glob(paste0(study_path,"V*/*",sample,"/"))
  sample_path <- Sys.glob(paste0(study_path,"V*/*",sample,"/","*.h5"))
  sample_path_file <- tail(strsplit(sample_path, split = "/")[[1]], n = 1)
  seuratSpatial[[sample]]<-Load10X_Spatial(
                                      sample_dir,
                                      filename = sample_path_file,
                                      assay = "Spatial",
                                      slice = sample,
                                      filter.matrix = TRUE,
                                      to.upper = FALSE
                                    )
  #THIS SETS UP META DATA 'orig.ident' as individual sample
  seuratSpatial[[sample]]$orig.ident <- sample
  #THIS SETS UP META DATA 'group' AS current sample_group
  seuratSpatial[[sample]]$group <- sample_group[[counter]]
  seuratSpatial[[sample]]$label <- sample_group[[counter]]
  counter<-counter+1
}
```

```{r data_pre_processing}
#plot overall counts - not in manuscript
pdf(file = paste0(save_path, study_name, "h1h2h3_P1_M1_overall_counts.pdf"))
  for(object in seuratSpatial){
    plot1 <- VlnPlot(object, features = "nCount_Spatial", pt.size = 0.1) + NoLegend()
    plot2 <- SpatialFeaturePlot(object, features = "nCount_Spatial") + theme(legend.position = "right")
    plot3 <- SpatialFeaturePlot(object, features = "nFeature_Spatial") + theme(legend.position = "right")
    print(wrap_plots(plot1, plot2, plot3))
  }
dev.off()
```

```{r SCTRansform,  warning=FALSE}
#Normalize data
for(sample in samples){
  seuratSpatial[[sample]] <- SCTransform(seuratSpatial[[sample]], assay = "Spatial", verbose = FALSE, vars.to.regress = c("nCount_Spatial", "nFeature_Spatial"))
}
```
Integrate only when looking at common signatures

```{r integrate_workflow_for_spatial}
#Integrate data
features <- SelectIntegrationFeatures(object.list = seuratSpatial, nfeatures = 3000)
seuratSpatial <- PrepSCTIntegration(object.list = seuratSpatial, anchor.features = features)
immune.anchors <- FindIntegrationAnchors(object.list = seuratSpatial, normalization.method = "SCT", anchor.features = features)
PKDL_merged <- IntegrateData(anchorset = immune.anchors, normalization.method = "SCT")
```


