
```{r setup, include=FALSE}
library(Seurat)
library(dplyr)
library(ggplot2)
library(patchwork)
library(sqldf)
library(dplyr)
library(RColorBrewer)
library(plotly)
library(spatstat)
library(gplots)
library(corrplot)
library(stringr)
library(VennDiagram)
library(grid)
library(reshape2)
library(ggplot2)
library(EnhancedVolcano)
library(ggpubr)

study_name<-"human_SLCL_Visium"
#PLEASE ADD YOUR WORKING PATH HERE
study_path<-"your_path_here/"

samples <-c("30i","35i","40i", "53i", "47i", "48i")
#, "57i")
sample_label <-c("P1","P2","P3", "P4", "P5", "P6")
#Create a sub-folder in your 
#work path where all outputs
#will be stored
save_path<-paste0(study_path,"R/")
save_on<-1
```

```{r read_RDS}
nd2117SLCL_skin_merged <- readRDS(paste0(save_path, "with47_48_integrated_nd2117slcl_dims15_res0.9_prepsct.rds"))
```

```{r recolour}
DefaultAssay(nd2117SLCL_skin_merged)<-"SCT"
new.cluster.ids <- c("mix","My1","B/fib","My2","TL","KC1","Fib","Fib","KC2","B","My3","Endothelial")

names(new.cluster.ids) <- levels(nd2117SLCL_skin_merged)
nd2117SLCL_skin_merged <- RenameIdents(nd2117SLCL_skin_merged, new.cluster.ids)
nd2117SLCL_skin_merged$morpho <- Idents(nd2117SLCL_skin_merged)

levels(Idents(nd2117SLCL_skin_merged))
ident_colours =c("mix" ="grey", "My1" = "#008000", "B/fib" ="#CD5C5C",'My2'='#ff9a36','TL'='#B95FBB', 'KC1'='#faf4cf',"Fib"='#F0E68C','KC2'='#E6E6FA', 'B'='#F68282','My3'='#25aff5',"Endothelial" ="#ADD8E6")
my_cols1 <- ident_colours[order(as.character(names(ident_colours)))]
```

```{r change_meta}
cell2location_abundances <- read.csv(paste0(save_path, "q05_cell_abundance_w_sf_barcoded.csv"))
rownames(cell2location_abundances)<-cell2location_abundances$spot_id
# [1] "spot_id"             "DC1"                 "DC2"                
#  [4] "DifferentiatedKC"    "DifferentiatedKC."   "F1"                 
#  [7] "F2"                  "F3"                  "ILC13"              
# [10] "ILC1NK"              "ILC2"                "Infmono"            
# [13] "LC1"                 "LC2"                 "LC3"                
# [16] "LC4"                 "LE1"                 "LE2"                
# [19] "Macro1"              "Macro2"              "Mastcell"           
# [22] "Melanocyte"          "MigDC"               "Mono"               
# [25] "NK"                  "Pericyte1noninflamm" "Pericyte2inflamm"   
# [28] "Plasma"              "ProliferatingKC"     "Schwann1"           
# [31] "Schwann2"            "Tc"                  "Th"                 
# [34] "Treg"                "UndifferentiatedKC." "VE1"                
# [37] "VE2"                 "VE3"                 "moDC1"              
# [40] "moDC2"               "moDC3"  
cell_types<-colnames(cell2location_abundances)
cell_types<-cell_types[2:length(cell_types)]


df<-cell2location_abundances[,cell_types]#_thresholded

# calculate the maximum of each column - Not applicable for this dataset
#df_max <- apply(df, 2, max)
#df_max <- colMaxs(df) requires a package
df_median <- apply(df, 2, median)

# sort the dataframe based on the mean values
df_sorted <- df[, order(df_median, decreasing = T)]

#Showing the top 20 most abundant cell types only
df_melt <- melt(df_sorted[,1:20])

pdf(paste0(save_path, "sorted_all_box_cell2space_sd22.2.1.pdf"), height = 10, width=7)
  ggplot(data = df_melt, aes(x = value, y = variable, fill = variable)) + 
        geom_boxplot() + 
        coord_flip()  + 
        theme_classic() + 
        theme(legend.position="none", axis.text.x = element_text(angle = 90, hjust = 1)) +
        #geom_vline(aes(xintercept = median(df_median)), col = "red", size = 0.3) +
        ylab(label = "") +
        xlab(label = "Cell2Location q05 abundances")
        scale_x_continuous(limits=c(0, 30), breaks=c(0, 5, 10, 15, 20,25, 30))
dev.off() 

nd2117SLCL_skin_merged<-AddMetaData(nd2117SLCL_skin_merged, metadata = cell2location_abundances)

```

```{r Extended_data_figure_2}
######Extended Data Figure 2a
items_to_process<-c("30i","35i","40i","48i","53i","47i")
listGraphs <- list()

for(item in items_to_process){
  obj <- subset(nd2117SLCL_skin_merged, subset = orig.ident == item)
  
  df<-obj@meta.data[,cell_types]#_thresholded

  # calculate the maximum of each column - Not applicable for this dataset
  #df_max <- apply(df, 2, max)
  #df_max <- colMaxs(df) requires a package
  df_median <- apply(df, 2, median)
  
  # sort the dataframe based on the mean values
  #df_sorted <- df[, order(df_max, decreasing = T)]
  df_sorted <- df[, order(df_median, decreasing = T)]
  df_melt <- melt(df_sorted[,1:20])
  

  print_item<-ggplot(data = df_melt, aes(x = value, y = variable, fill = variable)) + 
              geom_boxplot(outlier.size = 0.5) + 
              coord_flip()  + 
              theme_classic() + 
              theme(legend.position="none", axis.text.x = element_text(angle = 90, hjust = 1)) +
              #geom_vline(aes(xintercept = median(df_median)), col = "red", size = 0.3) +
              ylab(label = "") +
              xlab(label = "Cell2Location q05 abundances")  +
              ggtitle(label = item) +
              scale_x_continuous(limits=c(0, 30), breaks=c(0, 5, 10, 15, 20,25, 30))
  listGraphs[[item]] <- print_item
}
  
pdf(paste0(save_path,"Ext_Data_Fig_2a_patient_sorted_all_box_cell2space_sd22.2.1.pdf"), height = 10, width=7)  
  ggarrange(plotlist = listGraphs, ncol = 2, nrow = 3)
dev.off()

#Please note: You may encounter the following warning when running the above. Explanation for this is that we ahev exlcuded plotting 15 outliying spots in patient by patient plots to keep the maximum y-axis value at 30.
# Warning: Removed 2 rows containing non-finite values (`stat_boxplot()`).Warning: Removed 1 rows containing non-finite values (`stat_boxplot()`).Warning: Removed 12 rows containing non-finite values (`stat_boxplot()`).null device 

#Data extracted for Extended data figure 2b and then plotted on Graphpad
my1my2my3 <- subset(nd2117SLCL_skin_merged, subset = morpho %in% c("My1","My2","My3"))
my1my2m3_raw_abundances <- my1my2my3@meta.data[, c("morpho", cell_types)]
```

```{r spatial_maps}

celltypes_thresholded_my1_my2_my3 <-c("DC2","ILC1NK","ILC2","Macro1","Macro2","Mono","NK","Tc","Th","Treg")

pdf(paste0(save_path, "Ext_Data_Fig2c-l_celltypes_thresholded_my1_my2_my3_cell2space_sd22.2.1.pdf"), height =20, width=8)
  for(image_count in 1:length(nd2117SLCL_skin_merged@images)){
    image<-names(nd2117SLCL_skin_merged@images)[image_count]
    print(SpatialFeaturePlot(nd2117SLCL_skin_merged, features = celltypes_thresholded_my1_my2_my3, crop = F, image.alpha = 0, pt.size.factor = 1, alpha = c(0.1,2), images =image, ncol = 1, stroke = 0))
  }
dev.off()
```

```{r assigning spot ids}
summary(nd2117SLCL_skin_merged[["SCT"]]["CD274",])
summary(nd2117SLCL_skin_merged[["SCT"]]["IDO1",])

#higher than median values (for display use 1.2)
ido_intercept <- 1.1
#higher than zero values as all 
pdl1_intercept <- 0.5

pdf(paste0(save_path, "pdl1_ido1_overall_scatter.pdf"), height = 5, width=5)
 FeatureScatter(nd2117SLCL_skin_merged, feature1 = "IDO1", feature2 = "CD274",  jitter=3) + NoLegend() + geom_vline(aes(xintercept = (ido_intercept+0.1)), col = "red") + geom_hline(aes(yintercept = pdl1_intercept), col = "red")
dev.off()

ido_pdl<- list()


ido_pdl[["ido1lo_pdl1lo"]]<-subset(nd2117SLCL_skin_merged, subset = IDO1 < ido_intercept & CD274 < pdl1_intercept)
ido_pdl[["ido1lo_pdl1lo"]]

ido_pdl[["ido1hi_pdl1lo"]]<-subset(nd2117SLCL_skin_merged, subset = IDO1 > ido_intercept & CD274 < pdl1_intercept)
ido_pdl[["ido1hi_pdl1lo"]]

ido_pdl[["ido1hi_pdl1hi"]]<-subset(nd2117SLCL_skin_merged, subset = IDO1 > ido_intercept & CD274 > pdl1_intercept)
ido_pdl[["ido1hi_pdl1hi"]]

ido_pdl[["pdl1hi_ido1lo"]]<-subset(nd2117SLCL_skin_merged, subset = IDO1 < ido_intercept & CD274 > pdl1_intercept)
ido_pdl[["pdl1hi_ido1lo"]]

# my1my2<-subset(nd2117SLCL_skin_merged, subset = morpho %in% c("My1","My2"))
# my1only<-subset(nd2117SLCL_skin_merged, subset = morpho %in% c("My1"))
# my2only<-subset(nd2117SLCL_skin_merged, subset = morpho %in% c("My2"))
# my3only<-subset(nd2117SLCL_skin_merged, subset = morpho %in% c("My3"))
# all_but_myeloid<-subset(nd2117SLCL_skin_merged, subset = morpho %in% c("My1","My2","My3"), invert=T)
# 
# pdf(paste0(save_path, "pdl1_ido1_my1my2_scatter.pdf"), height = 5, width=5)
#    a<-FeatureScatter(my1my2, feature1 = "IDO1", feature2 = "CD274", cols = rep("black",10), jitter = 3) + NoLegend() + geom_vline(aes(xintercept = (ido_intercept+0.1)), col = "red", size = 0.3) + geom_hline(aes(yintercept = pdl1_intercept), col = "red", size = 0.3) + ggtitle(label = "My1_My2")
#    b<-FeatureScatter(my1only, feature1 = "IDO1", feature2 = "CD274", cols = rep("black",10), jitter = 3) + NoLegend() + geom_vline(aes(xintercept = (ido_intercept+0.1)), col = "red", size = 0.3) + geom_hline(aes(yintercept = pdl1_intercept), col = "red", size = 0.3) + ggtitle(label = "My1")
#    c<-FeatureScatter(my2only, feature1 = "IDO1", feature2 = "CD274", cols = rep("black",10), jitter = 3) + NoLegend() + geom_vline(aes(xintercept = (ido_intercept+0.1)), col = "red", size = 0.3) + geom_hline(aes(yintercept = pdl1_intercept), col = "red", size = 0.3) + ggtitle(label = "My2")
#    d<-FeatureScatter(my3only, feature1 = "IDO1", feature2 = "CD274", cols = rep("black",10), jitter = 3) + NoLegend() + geom_vline(aes(xintercept = (ido_intercept+0.1)), col = "red", size = 0.3) + geom_hline(aes(yintercept = pdl1_intercept), col = "red", size = 0.3) + ggtitle(label = "My3")
#    e<-FeatureScatter(all_but_myeloid, feature1 = "IDO1", feature2 = "CD274", cols = rep("black",10), jitter = 3) + NoLegend() + geom_vline(aes(xintercept = (ido_intercept+0.1)), col = "red", size = 0.3) + geom_hline(aes(yintercept = pdl1_intercept), col = "red", size = 0.3)+ ggtitle(label = "all_but_My")
#    ggarrange(a, b,c,d,e, ncol = 2, nrow = 3)
# dev.off()



items_to_process<-c("ido1lo_pdl1lo","ido1hi_pdl1lo","ido1hi_pdl1hi","pdl1hi_ido1lo")
listGraphs <- list()

for(item in items_to_process){
  ido_pdl[[item]]$ido_pdl<-item
  
  df<-ido_pdl[[item]]@meta.data[,cell_types]

  # calculate the maximum of each column -
  df_median <- apply(df, 2, median)
  
  # sort the dataframe based on the mean values
  df_sorted <- df[, order(df_median, decreasing = T)]
  #Showing the top 20 most abundant cell types only
  df_melt <- melt(df_sorted[,1:20])
  
  print_item <- ggplot(data = df_melt, aes(x = value, y = variable, fill = variable)) + 
                geom_boxplot(outlier.size = 0.5) + 
                coord_flip()  + 
                theme_classic() + 
                theme(legend.position="none", axis.text.x = element_text(angle = 90, hjust = 1)) +
                #geom_vline(aes(xintercept = median(df_median)), col = "red", size = 0.3) +
                ylab(label = "") +
                xlab(label = "Cell2Location q05 abundances")  +
                ggtitle(label = item) +
                scale_x_continuous(limits=c(0, 30), breaks=c(0, 5, 10, 15, 20,25, 30))
  listGraphs[[item]] <- print_item

}

pdf(paste0(save_path,"Ext_Data_Fig_5b-d_ido1pdl1_sorted_all_box_cell2space_sd22.2.1.pdf"), height = 10, width=7)
  ggarrange(plotlist = listGraphs, ncol = 2, nrow = 2)
dev.off()
```





